### ISSUE TITLE
Allow tasks to destroy themselves

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#289]
With the current implementation, instances can't destroy all the supporting resources[^1], because of interdependency. For example, after deleting a security group, it's impossible to issue more API calls because there is no network connection.

Possible solutions include:

* Using cloud-native templates like AWS CloudFormation, Google Cloud Deployment
Manager and Azure Resource Templates to let providers destroy everything.

* Leaving cheap and costless resources in the cloud, and running a garbage
collector in every invocation to delete resources from past tasks.

* Requiring users to explicitly delete resources after each task. This approach
is convenient with the launch/harvest lifecycle, but not for the CML runner.

**Comment by dacbd** [comment]
Do you have a good list of the particular resources that cause this issue?

My two cents is to allow those resources to be predefined by the user  (vpc, security grp rules, etc) so tpi doesn't need to clean them and users can have that extra control.

**Comment by 0x2b3bfa0** [comment]
Alternatively, why not add an explicit cleanup step at the end of workflows?

```yaml
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - run: cml runner create ···
  train:
    needs: deploy
    runs-on: self-hoster
    steps:
      - uses: iterative/setup-dvc@v1
      - run: dvc repro
  sweep:
    if: always()
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - run: cml runner delete ···
```
![Captura de pantalla 2022-03-14 a las 0 51 51](https://user-images.githubusercontent.com/11387611/158084784-8dfa32ed-d531-485b-891e-89d8d65299be.png)

On GitHub Actions, this can even be automated by using the [`post`](https://github.com/actions/checkout/blob/61b9e3751b92087fd0b06925ba6dd6314e06f089/action.yml#L74) functionality.
