### ISSUE TITLE
Easy way to list Azure and AWS needed permissions 

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#75]
Coming from [here](https://discord.com/channels/485586884165107732/728693131557732403/817377801232711691)

> what are the AWS permissions required by the terraform provider for cml?

**Comment by 0x2b3bfa0** [comment]
Seee also https://github.com/iterative/cml/issues/429#issuecomment-791641276

**Comment by casperdcl** [comment]
also vis. https://github.com/iterative/cml/issues/814#issuecomment-973113551

**Comment by 0x2b3bfa0** [comment]
# 🧙🏼‍♂️ [Kubernetes — Creating an isolated namespace](https://www.notion.so/iterative/Creating-an-isolated-namespace-e3e93c64ba204fdf96a28124ad519e0e)

If required, authentication can be configured through a narrowly scoped service account inside an ad-hoc namespace. Applying the following definitions will create a new namespace and an equally named service account, along with the required roles and role bindings:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: iterative
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: iterative
  name: iterative
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: iterative
  name: iterative
rules:
  -
    apiGroups:
      - ""
      - apps
      - batch
    resources:
      - jobs
      - pods
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: iterative
  name: iterative
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iterative
subjects:
- kind: ServiceAccount
  namespace: iterative
  name: iterative

```


>💡 *You can just save the configuration above in a file and apply it by running `kubectl apply --filename <file>` on your computer.*

### Generating a `kubeconfig` file for the created service account

After applying the above configuration, you can generate the required `kubeconfig`data by running the following script:

```bash
SERVER="$(
  kubectl get endpoints --output \\
    jsonpath="{.items[0].subsets[0].addresses[0].ip}"
)"

AUTHORITY="$(
  kubectl config view --raw --minify --flatten --output \\
    jsonpath='{.clusters[].cluster.certificate-authority-data}'
)"

SECRET="$(
  kubectl --namespace=iterative get serviceaccount iterative --output \\
    jsonpath="{.secrets[0].name}"
)"

TOKEN="$(
  kubectl get secret "$SECRET" --namespace=iterative --output \\
    jsonpath="{.data.token}" | base64 --decode
)"

(
  export KUBECONFIG="$(mktemp)"
  {
    kubectl config set-cluster cluster --server="<https://$SERVER>"
    kubectl config set clusters.cluster.certificate-authority-data "$AUTHORITY"
    kubectl config set-credentials iterative --token="$TOKEN"
    kubectl config set-context cluster --cluster=cluster --namespace=iterative --user=iterative
    kubectl config use-context cluster
  } > /dev/null
  cat "$KUBECONFIG" && rm "$_"
)

```

> 📖 *The code above is just an example and might fail for some managed Kubernetes providers; it's known to work on GKE, but your mileage may vary.*
